### ISSUE TITLE
Update site metadata

### ISSUE THREAD

**Issue by blindingstars** [JacobMGEvans/lake-county-tech-meetup#12]
Minor clarification: is this meant for Lake County, IL or Lakewood (village in McHenry County)? The repo name and Netlify name make me think the former, but I see allusions to Lakewood in `gatsby-config.js` and wanted to confirm before making a commit.

If this is intended for Lake County, the site title and description could use an update.

**Comment by JacobMGEvans** [comment]
Yeah, that was a mistake. I sometimes code very late at night 🤣 Its definitely Lake County. Feel free to make corrections wherever you see this discrepancy.
